runtime: custom
service: skywallet-astar-fe-service
env: flex

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

default_expiration: "4d 5h"

network:
  name: projects/metasky-prod/global/networks/metasky-prod
  subnetwork_name: asia-southeast1

resources:
  cpu: 1 #no of vcpu
  memory_gb: 2

liveness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 10
  success_threshold: 2
  initial_delay_sec: 300

readiness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 10
  success_threshold: 2
  app_start_timeout_sec: 300


# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 15
#   cool_down_period_sec: 180
#   cpu_utilization:
#     target_utilization: 0.6
#   target_concurrent_requests: 100


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

service_account: metasky-prod-service-account@metasky-prod.iam.gserviceaccount.com
