export enum screen {
  home = `Landed on Home Page`,
  nftDetail = `Landed on NFT Detail Page`,
  benefitsList = `Landed on Benefits List Page`,
  benefitsDetail = `Landed on Benefits Detail Page`,
  profile = `Landed on User Profile Page`,
  walletDetail = `Landed on Wallet Detail Page`,
  confirmOrder = `Landed on Confirm Order Page`,
  confirmTransfer = `Landed on Confirm Transfer Page`,
  sell = `Landed on Sell Page`,
  transactionDetails = `Landed on Transaction Details Page`,
  purchaseNft = `Landed on Purchase NFT Page`,
  marketplace = `Landed on Marketplace Page`,
  babbuScreen = `Landed on Babbu Page`,
  feedDetail = `Landed on Feed Detail`,
}

export enum EVENT_PAGE {
  LOGIN = `Login`,
  LOGIN_MOBILE = `Login Mobile`,
  OTP_VEERIFICATION = `OTP Verification`,
  ENTER_PIN = `Enter Pin`,
  WALLET = `Wallet`,
  HOME = `Home`,
  PROFILE = `User Profile Side Panel`,
  EDIT_PROFILE = `Edit Profile`,
  UPDATE_PRICE = `Update Price`,
  CHANGE_PIN = `Change PIN`,
  FORGET_PIN = `Forget PIN`,
  CREATE_PIN = `Create PIN`,
  CUSTOMER_SUPPORT = `Customer Support`,
  MY_REWARDS = `My Rewards`,
  TRANSFER = `Transfer`,
  SCAN = `Scan`,
  WALLET_DETAILS = `Wallet Details Bottom Sheet`,
  QR_CODE = `QR Code Bottom Sheet`,
  VIEW_ADDRESS = `View Address Bottom Sheet`,
  MORE_WALLET_LISTS = `More Wallets Bottom Sheet`,
  LOGOUT_CONFIRMATION = `Logout Confirmation Bottom Sheet`,
  AUTH_FLOW = `Auth Flow in Bottom Sheet`,
  SELL_FLOW = `Sell Bottom Sheet`,
  TRANSACTION = `Transaction`,
  FEED_DETAIL = `Feed Detail`,
  MARKET = `Market`,
  MARKET_LISTINGS = `Market Listings`,
  COLLECTION_DETAIL = `Collection Details`,
  COLLECTION_CLAIM_DETAIL = `Collection Claim Details`,
  PURCHASE_NFT = `Purchase NFT`,
  PROCEED_TO_PAYMENT = `Proceed to payment`,
  PREVIEW_PURCHASE = `Preview Purchase`,
  TRANSACTION_DETAIL = `Transaction Detail`,
  HOME_SCAN = `Home Scan`,
  CONFIRM_LOGOUT = `Confirm Logout`,
  MY_NFTS = `My NFTs`,
  NFT_DETAIL = `NFT Detail`,
  DELETE_LISTING = `Delete Listing`,
  ERROR = `Error Page`,
  CAMPAIGN_LANDING = `Campaign Landing`,
  CAMPAIGN_DETAILS = `Campaign Details`,
}

export enum CLICK {
  CONTINUE_WITH_OTHER_OPTIONS_LOGIN = `Continue using other options in Login`,
  CONTINUE_WITH_EMAIL = `Continue with Email`,
  CONTINUE_WITH_MOBILE = `Continue with Mobile Number`,
  CONTINUE_LOGIN = `Continue in Login`,
  RESEND_CODE = `Resend Code`,
  VALIDATE_CODE = `Validate Code`,
  NETWORK_DROPDOWN = `Network Dropdown`,
  SWITCH_ACCOUNT = `Switch Account`,
  FORGET_PIN = `Forget PIN`,
  CONTINUE_PIN = `Continue in Enter Pin`,
  GO_TO_WALLET = `Go to Wallet`,
  HAMBURGER_HOME = `Hamburger in Home`,
  EDIT_PROFILE = `Edit Profile`,
  SAVE_EDIT_PROFILE = `Save in Edit Profile`,
  YES_REJECT = `Yes Reject`,
  YES_DELETE = `Yes Delete`,
  UPDATE_PRICE = `Update Price`,
  SET_NEW_PIN = `Set New PIN`,
  CONTINUE_CHANGE_PIN = `Continue in Change Pin`,
  SET_PIN = `Set PIN`,
  TRANSFER_CLOSED = `Close in Transfer`,
  PAYMENT = `Payment button`,
  CONNECT_WALLET = `Connect Wallet`,
  VIEW_ADDRESS = `View Address`,
  BACK = `Back`,
  CLOSE_WALLET_DETAILS = `Close Wallet Details`,
  VIEW_QR_CODE = `View QR Code`,
  COPY_ADDRESS = `Copy Wallet Address`,
  LOGOUT_CONFIRMED = `Logout Confirmed`,
  SELL = `Sell`,
  CONFIRM_LISTING = `Confirm Listing`,
  CLOSE_SELL_FLOW = `Close Sell Flow`,
  ANNOUNCEMENT_BANNER = `Announcement Banner`,
  FEED_NEXT = `Next in Feed`,
  FEED_PREV = `Previous in Feed`,
  FEED_DETAIL = `Feed Details`,
  FEED_DETAIL_CLOSE = `Feed Close`,
  COLLECTION_CARD_Market = `Collection Card in Market`,
  VIEW_MORE_DETAILS = `View More Details`,
  NFT_CARD_MARKET_LISTINGS = `NFT Card in Market Listings`,
  BUY_NOW = `Buy Now`,
  CANCEL_PREVIEW_PURCHASE = `Cancel in Preview Purchase`,
  PURCHASE_PREVIEW_PURCHASE = `Purchase in Preview Purchase`,
  HISTORY = `History`,
  TRANSACTION_CARD = `Transaction Card`,
  SCAN = `Scan`,
  CONTINUE_HOME_SCAN = `Continue in Home Scan`,
  LOGOUT = `Logout`,
  CONFIRM_LOGOUT = `Confirm Logout`,
  CANCEL_LOGOUT = `Cancel Logout`,
  SEE_ALL = `See All in NFT Swiper`,
  NFT_CARD_MY_NFTS = `NFT Card in My NFTs`,
  COLLECTION_CARD_NFT_DETAIL = `Collection Card in NFT Detail`,
  CLAIM_COLLECTION_NFT = `Claim Collection NFT`,
  VIEW_IN_NFT_DETAIL = `View in NFT Detail`,
  DELETE_LISTING = `Delete Listing`,
  CANCEL_DELETE_LISTING = `Cancel in Delete Listing`,
  YES_DELETE_LISTING = `Yes Delete in Delete Listing`,
  ENTER_CONTEST = `Enter Contest`,
  BANNER = `Banner`,
  NFT = `NFT`,
  BUY_TICKET = `Buy Ticket`,
  BUY_BEER_BENEFIT = `Buy Beer Benefit`,
}

export enum EVENT_PROCESS {
  PAYMENT_INITIATED = `Payment Initiated`,
  COLLECTION_NFT_CLAIMED = `Claimed Collection NFT`,
}

export enum click {
  installApp = `Install App: Click`,
  announcementBanner = `Announcement: Click`,
  homepageTransfer = `Clicked on Home Page Transfer`,
  sendNftTransfer = `Clicked on Send NFT Transfer`,
  transferPopUpClose = `Clicked on Transfer Pop Up Close`,
  rechargeWallet = `Clicked on Recharge Wallet`,
  backOnConfirmTransfer = `Clicked on Back on Confirm Transfer`,
  proceedToPayment = `Clicked on Proceed To Payment`,
  sendNftDetails = `Clicked on Send`,
  sellNftDetails = `Clicked on Sell`,
  confirmListing = `Clicked on Confirm Listing`,
  backOnSell = `Clicked on Back on Sell`,
  purchase = `Clicked on Purchase`,
  purchaseSuccess = `Purchased Successfully`,
  purchaseCancel = `Clicked on Cancel Purchase`,
  benefitsAccess = `Clicked on Benefits Access Now `,
  babbuScreenSubmit = `Clicked on Babbu Submit`,
  collection = `Clicked on Collection`,
  feedNext = `Clicked on Next in Feed`,
  feedPrev = `Clicked on Previous in Feed`,
  feedDetail = `Clicked on Feed Details`,
  feedDetailClose = `Clicked on Feed Close`,
}

export enum swipe {
  swipeToTransfer = `Swiped Swipe To Transfer`,
  swipeToListNft = `Swiped Swipe To List NFT`,
}

export enum bottomSheet {}
