export enum Pages {
  HOME = `/`,
  NEW_Home = `/home`,
  CLUBS = `/clubs`,
  TOKEN_LIST = `/tokens-list`,
  TOKEN_DETAILS = `/token-details`,
  NFT_LIST = `/nfts-list/own`,
  NFT_DETAILS = `/nft-details`,
  TRANSACTION = `/transaction`,
  TRANSACTION_DETAILS = `/transaction-details`,
  COLLECTION_DETAILS = `/collection/details`,
  COLLECTIONS = `/collection`,
  FILTER = `/filter`,
  BENEFITS = `/benefits`,
  ALL_BENEFITS = `/benefits/own/all`,
  BENEFITS_DETAILS = `/benefit-details`,
  PURCHASE_NFT = `/purchase-nft`,
  LOGIN = `/login`,
  CONSUMABLE_NFTS = `/consumable-nfts`,
  CONTACTUS = `/contact-support`,
  PAGE_NOT_FOUND = `/404`,
  REFER_AND_EARN = `/refer-and-earn`,
  MY_REWARD = `/my-reward`,
  FORGOT_PIN = `/forgot-pin`,
  DECENTRO_QR = `/decentro-qr`,
  FEED_DETAILS = `/feed-detail`,
  UPDATES = `/updates`,
}
