# .github/workflows/deploy.yaml

name: gcp-skywallet-xrp-fe-stage-deployment
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
         project_id: ${{ 'metasky-stage' }}
      - name: Prepare docker file
        run: |-
            cp -a ./DockerfileStage ./Dockerfile
      - name: Authentication
        uses: 'google-github-actions/auth@v1'
        with:
         project_id: ${{ 'metasky-stage' }}
         credentials_json: ${{ secrets.GCP_APP_ENGINE_CREDS }}
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
         deliverables: stage-app.yaml
         project_id: ${{ 'metasky-stage' }}
         promote: true
        env:
         CLOUDSDK_APP_CLOUD_BUILD_TIMEOUT: 1800 # 30 minutes
